function [Planet] = bodysort()
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
     Planet = struct(...    
       'name',' '    ...    
      ,'mass',0      ...    Mass                [kg] 
      ,'radius',0    ...    Radius @ Equator    [m]
      ,'P1',[0 0 0]  ...             
      ,'H',[0 0 0]   ...     
      );
      end
